### ISSUE TITLE
Only support one tcp port in config file?

### ISSUE THREAD

**Issue by ZhangLimengLimeng** [fangdingjun/wstunnel#3]
hi，in the yaml file, I write in like this:
proxy_config:
    - listen: tcp://192.168.1.1:3333
      remote: ws://192.168.1.2:9001/u1
    - listen: tcp://192.168.1.1:3334
      remote: ws://192.168.1.2:9001/u2

only the last one can be use, the error is "bind: address already in use"

**Comment by fangdingjun** [comment]
It supports multiple forwards at same time, may be your config file is not the valid yaml format

like python, yaml use indentation to identify the level too

you must make the correct indent


the valid config file looks like this:

```
proxy_config:
   -
       listen: tcp://192.168.1.1:3333
       remote: ws://192.168.1.2:9001/u1
   - 
       listen: tcp://192.168.1.1:3334
       remote: ws://192.168.1.2:9001/u2
```
